// Image 44: System.Numerics.dll - Assembly: System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - Types 15302-15314
[assembly: System.Reflection.AssemblyCompany("Mono development team")]
[assembly: System.Reflection.AssemblyCopyright("(c) Various Mono authors")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Numerics.dll")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyDescription("System.Numerics.dll")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyProduct("Mono Common Language Infrastructure")]
[assembly: System.Reflection.AssemblyTitle("System.Numerics.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]