// Image 14: System.Core.dll - Assembly: System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e - Types 11955-12609
[assembly: System.Reflection.AssemblyCompany("Mono development team")]
[assembly: System.Reflection.AssemblyCopyright("(c) Various Mono authors")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Core.dll")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyDescription("System.Core.dll")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyKeyFile("../silverlight.pub")]
[assembly: System.Reflection.AssemblyProduct("Mono Common Language Infrastructure")]
[assembly: System.Reflection.AssemblyTitle("System.Core.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]