// Image 39: System.Drawing.dll - Assembly: System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a - Types 15087-15098
[assembly: System.Reflection.AssemblyCompany("Mono development team")]
[assembly: System.Reflection.AssemblyCopyright("(c) Various Mono authors")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Drawing.dll")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyDescription("System.Drawing.dll")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyProduct("Mono Common Language Infrastructure")]
[assembly: System.Reflection.AssemblyTitle("System.Drawing.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComCompatibleVersion(1, 0, 3300, 0)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(System.Runtime.CompilerServices.CompilationRelaxations.NoStringInterning)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.Dependency("System,", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]