// Image 28: Unity.UnifiedRayTracing.Runtime.dll - Assembly: Unity.UnifiedRayTracing.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 14228-14330
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Testing.UnifiedRayTracing.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Testing.UnifiedRayTracing.Performance")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UnifiedRayTracing.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Universal.SurfaceCache.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-editor-testable")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.HighDefinition.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Universal.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Universal.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.SurfaceCache.Runtime")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]