// Image 12: Unity.Collections.dll - Assembly: Unity.Collections, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 11420-11764
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.IgnoresAccessChecksTo("UnityEngine.BurstModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Burst.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Collections.BurstCompatibilityTestCodeGen")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Collections.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Collections.CodeGen")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Collections.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Collections.PerformanceTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.CodeGen")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.Graphics")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.Hybrid")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Runtime.IO.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Runtime.UnityInstance")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Scenes")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Scenes.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Samples.GridPath.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.PerformanceTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.GPUDriven.Runtime")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]