// Image 19: DOTween.dll - Assembly: DOTween, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null - Types 13338-13539
[assembly: System.Reflection.AssemblyCompany("Demigiant")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \u00A9 Daniele Giardini, 2014")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyProduct("DOTween")]
[assembly: System.Reflection.AssemblyTitle("DOTween")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.InteropServices.Guid("807e068c-2a0e-4c81-a303-4b4fd3924511")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DOTweenEditor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DOTween43")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DOTween46")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DOTween50")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DOTweenPro")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DOTweenProEditor")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]