// Image 15: UnityEngine.TextCoreTextEngineModule.dll - Assembly: UnityEngine.TextCoreTextEngineModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 12610-12729
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-testable")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextMeshPro")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextCore.FontEngine.Tools")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.TextCoreModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.TextCoreTextModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.TextCore.Tools")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextMeshPro.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.FontEngine.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.PlayModeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElementsModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.ImguiModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UI.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("EditorGUI.Tests.Playmode")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.Controls")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.Utils")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextCore.Tests")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETStandard,Version=v2.1")]
[assembly: UnityEngine.UnityEngineModuleAssembly]