// Image 2: UnityEngine.UIElementsModule.dll - Assembly: UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 3783-5298
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: Unity.Properties.GeneratePropertyBagsForTypesQualifiedWith(typeof(UnityEngine.UIElements.IDataSourceViewHashProvider), Unity.Properties.TypeGenerationOptions.None | Unity.Properties.TypeGenerationOptions.ValueType | Unity.Properties.TypeGenerationOptions.ReferenceType | Unity.Properties.TypeGenerationOptions.Default)]
[assembly: Unity.Properties.GeneratePropertyBagsForTypesQualifiedWith(typeof(UnityEngine.UIElements.INotifyBindablePropertyChanged), Unity.Properties.TypeGenerationOptions.None | Unity.Properties.TypeGenerationOptions.ValueType | Unity.Properties.TypeGenerationOptions.ReferenceType | Unity.Properties.TypeGenerationOptions.Default)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Samples.StarterAssets.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.VectorGraphicsModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Modules.VectorGraphics.Tests.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Universal.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Universal.2D.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Samples.StarterAssets")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UI.TestFramework.Runtime.InternalAccessTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Samples.UIToolkit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.InternalAPIEngineBridge.001")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.InternalAPIEngineBridge.002")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.InternalAPIEngineBridge.003")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Hierarchy.PerformanceTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.HierarchyModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UI")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Modules.InputForUI.Tests.Playmode")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UI.TestFramework.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.Bindings")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-testable")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.TestComponents")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.Controls")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.RuntimeTests.Controls")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.RuntimeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.PlayModeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.StyleSheets")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.Utils")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.UXML")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElements.Tests.Base")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETStandard,Version=v2.1")]
[assembly: UnityEngine.UnityEngineModuleAssembly]