// Image 50: UnityEngine.TextCoreFontEngineModule.dll - Assembly: UnityEngine.TextCoreFontEngineModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 15505-15532
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextCore.FontEngine.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextCore")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-testable")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextMeshPro")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.TextCoreTextEngineModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.FontEngine.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextCore.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextCore.FontEngine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextCore.FontEngine.Tools")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETStandard,Version=v2.1")]
[assembly: UnityEngine.UnityEngineModuleAssembly]