// Image 43: UnityEngine.InputForUIModule.dll - Assembly: UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 15251-15301
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.PlayModeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.InputSystem.ForUI")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.InputSystem.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.InputSystem.IntegrationTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElementsModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Samples.StarterAssets.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Samples.UIToolkit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Modules.InputForUI.Tests.Common")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Modules.InputForUI.Tests.Playmode")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Modules.InputForUI.Tests.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.EditorTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.RuntimeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.XR.Interaction.Toolkit.Samples.StarterAssets")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETStandard,Version=v2.1")]
[assembly: UnityEngine.UnityEngineModuleAssembly]