// Image 30: UnityEngine.PropertiesModule.dll - Assembly: UnityEngine.PropertiesModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 14428-14600
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.EditorTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.UIElements.RuntimeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.UIElementsModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UIElementsModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Properties.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Properties.Reflection.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Properties.CodeGen.IntegrationTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.PropertiesModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("PropertyBags.GenerationTests")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETStandard,Version=v2.1")]
[assembly: UnityEngine.UnityEngineModuleAssembly]