// Image 29: Unity.2D.Animation.Runtime.dll - Assembly: Unity.2D.Animation.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 14331-14427
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.IgnoresAccessChecksTo("UnityEngine.BurstModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.Animation.Tests.EditorTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.Animation.Tests.RuntimeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.Animation.Tests.RuntimePerf")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.Animation.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.IK.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.IK.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.IK.Tests.RuntimeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.PsdImporter.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.Psdimporter.Tests.EditorTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Universal.2D.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.2D.Animation.Profiler")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]