// Image 16: Unity.RenderPipelines.GPUDriven.Runtime.dll - Assembly: Unity.RenderPipelines.GPUDriven.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 12730-13007
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.IgnoresAccessChecksTo("UnityEngine.BurstModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.TestTools.Graphics.Contexts")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Entities.Graphics")]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.FindNonRegisteredInstanceIDsJob<UnityEngine.Rendering.MeshInfo>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.FindNonRegisteredInstanceIDsJob<UnityEngine.Rendering.GPUDrivenMaterial>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.ParallelSortExtensions.RadixSortBucketCountJob<int>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.ParallelSortExtensions.RadixSortBucketCountJob<ulong>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.ParallelSortExtensions.RadixSortBatchPrefixSumJob<int>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.ParallelSortExtensions.RadixSortBatchPrefixSumJob<ulong>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.ParallelSortExtensions.RadixSortBucketSortJob<int>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(UnityEngine.Rendering.ParallelSortExtensions.RadixSortBucketSortJob<ulong>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.Collections.SortJob<int, Unity.Collections.NativeSortExtension.DefaultComparer<int>>))]
[assembly: Unity.Jobs.RegisterGenericJobType(typeof(Unity.Collections.SortJob<ulong, Unity.Collections.NativeSortExtension.DefaultComparer<ulong>>))]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]