// Image 47: System.Xml.Linq.dll - Assembly: System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 - Types 15375-15412
[assembly: System.Reflection.AssemblyCompany("Mono development team")]
[assembly: System.Reflection.AssemblyCopyright("(c) Various Mono authors")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Xml.Linq.dll")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyDescription("System.Xml.Linq.dll")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.17020")]
[assembly: System.Reflection.AssemblyKeyFile("../winfx.pub")]
[assembly: System.Reflection.AssemblyProduct("Mono Common Language Infrastructure")]
[assembly: System.Reflection.AssemblyTitle("System.Xml.Linq.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(System.Runtime.CompilerServices.CompilationRelaxations.NoStringInterning)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]