// Image 83: System.Runtime.CompilerServices.Unsafe.dll - Assembly: System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a - Types 15957-15961
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyCopyright("\u00A9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyDescription("System.Runtime.CompilerServices.Unsafe")]
[assembly: System.Reflection.AssemblyFileVersion("6.100.225.20307")]
[assembly: System.Reflection.AssemblyInformationalVersion("6.1.2")]
[assembly: System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\u00AE .NET Framework")]
[assembly: System.Reflection.AssemblyTitle("System.Runtime.CompilerServices.Unsafe")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]