// Image 78: UnityEngine.VideoModule.dll - Assembly: UnityEngine.VideoModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 15895-15912
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Audio.DSPGraph.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Audio.DSPGraph")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VideoTesting")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-testable")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.MediaModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.VideoModule")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Video.PlayModeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Video.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Video.EditModeTests")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETStandard,Version=v2.1")]
[assembly: UnityEngine.UnityEngineModuleAssembly]