// Image 3: Unity.RenderPipelines.Core.Runtime.dll - Assembly: Unity.RenderPipelines.Core.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 5299-6022
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Runtime.Shared")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.GraphicTests.Performance.RPCore.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.GraphicTests.Performance.Universal.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Rendering.PathTracing.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PathTracing.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.SurfaceCache.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SRPSmoke.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SRPSmoke.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SRPSmoke.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-Editor-testable")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Universal.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.Core.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]