/*
 * Generated code file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
 */

using System;
using System.Collections;
using System.ComponentModel;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Image 11: System.Data.dll - Assembly: System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - Types 11180-11419

namespace System.Data
{
	[DefaultEvent("CollectionChanged")]
	public sealed class ConstraintCollection : InternalDataCollectionBase // TypeDefIndex: 11220
	{
		// Fields
		private readonly DataTable _table; // 0x10
		private readonly ArrayList _list; // 0x18
		private int _defaultNameIndex; // 0x20
		private CollectionChangeEventHandler _onCollectionChanged; // 0x28
		private Constraint[] _delayLoadingConstraints; // 0x30
		private bool _fLoadForeignKeyConstraintsOnly; // 0x38
	
		// Properties
		protected override ArrayList List { get; } // 0x00000001802F8EC0-0x00000001802F8ED0 
		public Constraint this[int index] { get => default; } // 0x00000001818652C0-0x00000001818653E0 
		internal DataTable Table { get; } // 0x0000000180377550-0x0000000180377560 
		public Constraint this[string name] { get => default; } // 0x00000001818653E0-0x00000001818654E0 
	
		// Constructors
		internal ConstraintCollection(DataTable table); // 0x0000000181865210-0x00000001818652C0
	
		// Methods
		public void Add(Constraint constraint); // 0x0000000181862E70-0x0000000181862E80
		internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign); // 0x0000000181862F40-0x0000000181863640
		public Constraint Add(string name, DataColumn[] columns, bool primaryKey); // 0x0000000181862E80-0x0000000181862F40
		private void AddUniqueConstraint(UniqueConstraint constraint); // 0x0000000181862D70-0x0000000181862E70
		private void AddForeignKeyConstraint(ForeignKeyConstraint constraint); // 0x0000000181862CF0-0x0000000181862D70
		private bool AutoGenerated(Constraint constraint); // 0x0000000181863700-0x00000001818637C0
		private void ArrayAdd(Constraint constraint); // 0x0000000181863640-0x0000000181863690
		private void ArrayRemove(Constraint constraint); // 0x0000000181863690-0x00000001818636E0
		internal string AssignName(); // 0x00000001818636E0-0x0000000181863700
		private void BaseAdd(Constraint constraint); // 0x00000001818637C0-0x00000001818638B0
		private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength); // 0x00000001818638B0-0x0000000181863AD0
		private void BaseRemove(Constraint constraint); // 0x0000000181863AD0-0x0000000181863E20
		internal bool CanRemove(Constraint constraint, bool fThrowException); // 0x0000000181863E20-0x0000000181863E50
		public void Clear(); // 0x0000000181863E50-0x00000001818642E0
		public bool Contains(string name); // 0x0000000181864380-0x00000001818643A0
		internal bool Contains(string name, bool caseSensitive); // 0x00000001818643A0-0x00000001818644D0
		internal Constraint FindConstraint(Constraint constraint); // 0x00000001818644D0-0x00000001818646A0
		internal UniqueConstraint FindKeyConstraint(DataColumn[] columns); // 0x0000000181864800-0x0000000181864940
		internal UniqueConstraint FindKeyConstraint(DataColumn column); // 0x0000000181864940-0x0000000181864A70
		internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns); // 0x00000001818646A0-0x0000000181864800
		private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2); // 0x00000001818642E0-0x0000000181864380
		internal int InternalIndexOf(string constraintName); // 0x0000000181864A70-0x0000000181864C80
		private string MakeName(int index); // 0x0000000181864C80-0x0000000181864D10
		private void OnCollectionChanged(CollectionChangeEventArgs ccevent); // 0x000000018136EED0-0x000000018136EEF0
		internal void RegisterName(string name); // 0x0000000181864D10-0x0000000181864F40
		public void Remove(Constraint constraint); // 0x0000000181864F40-0x0000000181865100
		internal void UnregisterName(string name); // 0x0000000181865100-0x0000000181865210
	}
}
