/*
 * Generated code file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
 */

using System;
using System.Collections;
using System.ComponentModel;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Xml;

// Image 11: System.Data.dll - Assembly: System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 - Types 11180-11419

namespace System.Data
{
	internal sealed class XmlTreeGen // TypeDefIndex: 11340
	{
		// Fields
		private ArrayList _constraintNames; // 0x10
		private Hashtable _namespaces; // 0x18
		private Hashtable _autogenerated; // 0x20
		private Hashtable _prefixes; // 0x28
		private DataSet _ds; // 0x30
		private ArrayList _tables; // 0x38
		private ArrayList _relations; // 0x40
		private XmlDocument _dc; // 0x48
		private XmlElement _sRoot; // 0x50
		private int _prefixCount; // 0x58
		private SchemaFormat _schFormat; // 0x5C
		private string _filePath; // 0x60
		private string _fileName; // 0x68
		private string _fileExt; // 0x70
		private XmlElement _dsElement; // 0x78
		private XmlElement _constraintSeparator; // 0x80
		private Converter<Type, string> _targetConverter; // 0x88
	
		// Constructors
		internal XmlTreeGen(SchemaFormat format); // 0x00000001818D8340-0x00000001818D83F0
	
		// Methods
		internal static void AddExtendedProperties(PropertyCollection props, XmlElement node); // 0x00000001818CB8D0-0x00000001818CB8E0
		internal static void AddExtendedProperties(PropertyCollection props, XmlElement node, Type type); // 0x00000001818CB8E0-0x00000001818CBF10
		internal void AddXdoProperties(object instance, XmlElement root, XmlDocument xd); // 0x00000001818CBF10-0x00000001818CC0D0
		internal void AddXdoProperty(PropertyDescriptor pd, object instance, XmlElement root, XmlDocument xd); // 0x00000001818CC0D0-0x00000001818CC9D0
		internal static string XmlDataTypeName(Type type); // 0x00000001818D7B10-0x00000001818D8310
		private void GenerateConstraintNames(DataTable table, bool fromTable); // 0x00000001818CEA50-0x00000001818CEE70
		private void GenerateConstraintNames(ArrayList tables); // 0x00000001818CE730-0x00000001818CE820
		private void GenerateConstraintNames(DataSet ds); // 0x00000001818CE820-0x00000001818CEA50
		private static bool _PropsNotEmpty(PropertyCollection props); // 0x00000001818D8310-0x00000001818D8340
		private bool HaveExtendedProperties(DataSet ds); // 0x00000001818D33F0-0x00000001818D35E0
		internal void WriteSchemaRoot(XmlDocument xd, XmlElement rootSchema, string targetNamespace); // 0x00000001818D78E0-0x00000001818D7B10
		internal static void ValidateColumnMapping(Type columnType); // 0x00000001818D7860-0x00000001818D78E0
		internal void SetupAutoGenerated(DataSet ds); // 0x00000001818D6AA0-0x00000001818D6CD0
		internal void SetupAutoGenerated(ArrayList dt); // 0x00000001818D7680-0x00000001818D7760
		internal void SetupAutoGenerated(DataTable dt); // 0x00000001818D6CD0-0x00000001818D7680
		private void CreateTablesHierarchy(DataTable dt); // 0x00000001818CD5E0-0x00000001818CD8D0
		private void CreateRelations(DataTable dt); // 0x00000001818CD320-0x00000001818CD5E0
		private DataTable[] CreateToplevelTables(); // 0x00000001818CD8D0-0x00000001818CDC00
		internal void SchemaTree(XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, bool writeHierarchy); // 0x00000001818D3F30-0x00000001818D66D0
		internal XmlElement SchemaTree(XmlDocument xd, DataTable dt); // 0x00000001818D3A00-0x00000001818D3F30
		internal XmlElement FillDataSetElement(XmlDocument xd, DataSet ds, DataTable dt); // 0x00000001818CDC00-0x00000001818CE2F0
		internal void SetPath(XmlWriter xw); // 0x00000001818D6800-0x00000001818D6AA0
		internal void Save(DataSet ds, XmlWriter xw); // 0x00000001818D3900-0x00000001818D3930
		internal void Save(DataTable dt, XmlWriter xw); // 0x00000001818D3930-0x00000001818D3A00
		internal void Save(DataSet ds, DataTable dt, XmlWriter xw); // 0x00000001818D3780-0x00000001818D37A0
		internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy); // 0x00000001818D3620-0x00000001818D3780
		internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy, Converter<Type, string> multipleTargetConverter); // 0x00000001818D37A0-0x00000001818D3900
		internal XmlElement HandleRelation(DataRelation rel, XmlDocument dc); // 0x00000001818D0090-0x00000001818D06A0
		private static XmlElement FindSimpleType(XmlElement schema, string name); // 0x00000001818CE2F0-0x00000001818CE420
		internal XmlElement GetSchema(string NamespaceURI); // 0x00000001818CEE70-0x00000001818CF100
		internal void HandleColumnType(DataColumn col, XmlDocument dc, XmlElement root, XmlElement schema); // 0x00000001818CF100-0x00000001818CF580
		internal void AddColumnProperties(DataColumn col, XmlElement root); // 0x00000001818CB300-0x00000001818CB8D0
		private string FindTargetNamespace(DataTable table); // 0x00000001818CE420-0x00000001818CE540
		internal XmlElement HandleColumn(DataColumn col, XmlDocument dc, XmlElement schema, bool fWriteOrdinal); // 0x00000001818CF580-0x00000001818D0090
		internal static string TranslateAcceptRejectRule(AcceptRejectRule rule); // 0x00000001818D7760-0x00000001818D77C0
		internal static string TranslateRule(Rule rule); // 0x00000001818D77C0-0x00000001818D7860
		internal void AppendChildWithoutRef(XmlElement node, string Namespace, XmlElement el, string refString); // 0x00000001818CC9D0-0x00000001818CCA90
		internal XmlElement FindTypeNode(XmlElement node, string strType); // 0x00000001818CE540-0x00000001818CE730
		internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema); // 0x00000001818D3160-0x00000001818D3180
		private bool HasMixedColumns(DataTable table); // 0x00000001818D3180-0x00000001818D33F0
		internal static bool AutoGenerated(DataColumn col); // 0x00000001818CCEF0-0x00000001818CD320
		internal static bool AutoGenerated(DataRelation rel); // 0x00000001818CCDD0-0x00000001818CCEF0
		internal static bool AutoGenerated(UniqueConstraint unique); // 0x00000001818CCA90-0x00000001818CCB70
		private bool AutoGenerated(ForeignKeyConstraint fk); // 0x00000001818CCB70-0x00000001818CCB80
		internal static bool AutoGenerated(ForeignKeyConstraint fk, bool checkRelation); // 0x00000001818CCB80-0x00000001818CCDD0
		private bool IsAutoGenerated(object o); // 0x00000001818D35E0-0x00000001818D3620
		internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema, bool genNested); // 0x00000001818D06A0-0x00000001818D3160
		private void SetMSDataAttribute(XmlElement root, Type type); // 0x00000001818D66D0-0x00000001818D6800
	}
}
