// Image 87: System.Configuration.dll - Assembly: System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a - Types 15976-15985
[assembly: System.Reflection.AssemblyCompany("Mono development team")]
[assembly: System.Reflection.AssemblyCopyright("(c) Various Mono authors")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Configuration.dll")]
[assembly: System.Reflection.AssemblyDescription("System.Configuration.dll")]
[assembly: System.Reflection.AssemblyFileVersion("4.8.3761.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.8.3761.0")]
[assembly: System.Reflection.AssemblyProduct("Mono Common Language Infrastructure")]
[assembly: System.Reflection.AssemblyTitle("System.Configuration.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComCompatibleVersion(1, 0, 3300, 0)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPaths(System.Runtime.InteropServices.DllImportSearchPath.System32 | System.Runtime.InteropServices.DllImportSearchPath.AssemblyDirectory | System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]